// Vue/src/components/DataGridLocalData.vue
<script setup lang="ts">
import DxDataGrid, {
  DxColumn,
  DxSorting,
  DxRowDragging,
  DxSelection,
} from 'devextreme-vue/data-grid';
import type { DxDataGridTypes } from 'devextreme-vue/data-grid';
import type { Customer } from '../data';
import { customers } from '../data';
import { getVisibleRowValues } from '@/utils';

const props = defineProps({
  shouldClearSelection: Boolean,
});

const keyExpr: keyof Customer = 'ID';

function reorder(e: DxDataGridTypes.RowDraggingReorderEvent): void {
  const fullDataToInsert: Customer[] = [];
  e.itemData?.forEach((rowData: Customer) => {
    const indexToRemove = customers.findIndex(
      (item: Customer) => item[keyExpr] === rowData[keyExpr]
    );
    fullDataToInsert.push(customers[indexToRemove]);
    customers.splice(indexToRemove, 1);
  });
  const toIndex = calculateToIndex(customers, e);
  customers.splice(toIndex, 0, ...fullDataToInsert);
  e.component.refresh();
  if (props.shouldClearSelection) e.component.clearSelection();
}
function dragStart(e: DxDataGridTypes.RowDraggingStartEvent): void {
  const selectedData: Customer[] = e.component.getSelectedRowsData();
  e.itemData = getVisibleRowValues(selectedData, e.component);
  e.cancel = !canDrag(e);
}
function dragChange(e: DxDataGridTypes.RowDraggingChangeEvent): void {
  e.cancel = !canDrop(e);
}
function canDrag(e: DxDataGridTypes.RowDraggingStartEvent): boolean {
  const visibleRows = e.component.getVisibleRows();
  return visibleRows.some((r) => r.isSelected && r.rowIndex === e.fromIndex);
}
function canDrop(e: DxDataGridTypes.RowDraggingChangeEvent): boolean {
  const visibleRows = e.component.getVisibleRows();
  return !visibleRows.some((r) => r.isSelected && r.rowIndex === e.toIndex);
}
function calculateToIndex(
  dataArray: Customer[],
  e: DxDataGridTypes.RowDraggingReorderEvent
): number {
  const visibleRows = e.component.getVisibleRows();
  const toIndex = dataArray.findIndex(
    (item) => item[keyExpr] === visibleRows[e.toIndex].data[keyExpr]
  );
  return e.fromIndex >= e.toIndex ? toIndex : toIndex + 1;
}

</script>
<template>
  <DxDataGrid
    :data-source="customers"
    key-expr="ID"
  >
    <DxRowDragging
      :allow-reordering="true"
      :on-reorder="reorder as () => void"
      :on-drag-change="dragChange as () => void"
      :on-drag-start="dragStart as () => void"
      drag-template="dragItems"
    />
    <template #dragItems="{ data }">
      <table className="drag-container">
        <tbody>
          <tr
            v-for="item in data.itemData"
            class="dragged-item"
            :key="item[keyExpr]"
          >
            <td
              v-for="key in Object.keys(item)"
              :key="item[keyExpr] + key"
            >
              {{ item[key] }}
            </td>
          </tr>
        </tbody>
      </table>
    </template>
    <DxSelection mode="multiple"/>
    <DxSorting mode="none"/>
    <DxColumn
      data-field="ID"
      :width="55"
    />
    <DxColumn data-field="CompanyName"/>
    <DxColumn data-field="Address"/>
    <DxColumn data-field="City"/>
    <DxColumn data-field="State"/>
  </DxDataGrid>
</template>

// React/src/DataGridLocalData.tsx
import { useCallback } from 'react';
import DataGrid, {
  Column, RowDragging, Sorting, Selection, type DataGridTypes,
} from 'devextreme-react/data-grid';
import type { DragTemplateData } from 'devextreme/ui/draggable';
import notify from 'devextreme/ui/notify';
import type { Customer } from './data';
import { customers } from './data';
import type { GridDemoComponentProps } from './App';
import { getVisibleRowValues } from './utils';

const keyExpr: keyof Customer = 'ID';

function draggedItemsRender(data: DragTemplateData): JSX.Element {
  const draggedItems = data.itemData.map((item: Customer) => {
    const cellValues = (Object.keys(item) as (keyof Customer)[]).map((key: keyof Customer) => <td key={item.ID.toString() + String(item[key])}>{item[key]}</td>);
    return (<tr key={`row${item.ID}`} className="dragged-item">{cellValues}</tr>);
  });
  return (<table className="drag-container">
    <tbody>{draggedItems}</tbody>
  </table>);
}

function canDrag(e: DataGridTypes.RowDraggingStartEvent): boolean {
  const visibleRows = e.component.getVisibleRows();
  return visibleRows.some((r) => r.isSelected && r.rowIndex === e.fromIndex);
}
function canDrop(e: DataGridTypes.RowDraggingChangeEvent): boolean {
  const visibleRows = e.component.getVisibleRows();
  return !visibleRows.some((r) => r.isSelected && r.rowIndex === e.toIndex);
}
function dragStart(e: DataGridTypes.RowDraggingStartEvent): void {
  const selectedData: Customer[] = e.component.getSelectedRowsData();
  e.itemData = getVisibleRowValues(selectedData, e.component);
  e.cancel = !canDrag(e);
}
function dragChange(e: DataGridTypes.RowDraggingChangeEvent): void {
  e.cancel = !canDrop(e);
}
function calculateToIndex(dataArray: Customer[], e: DataGridTypes.RowDraggingChangeEvent): number {
  const visibleRows = e.component.getVisibleRows();
  const toIndex = dataArray.findIndex((item) => item[keyExpr] === visibleRows[e.toIndex].data[keyExpr]);
  return e.fromIndex >= e.toIndex ? toIndex : toIndex + 1;
}

function DataGridLocalData(props: GridDemoComponentProps): JSX.Element {
  const reorder = useCallback((e: DataGridTypes.RowDraggingReorderEvent): void => {
    const fullDataToInsert: Customer[] = [];
    e.itemData?.forEach((rowData: Customer) => {
      const indexToRemove = customers.findIndex((item: Customer) => item[keyExpr] === rowData[keyExpr]);
      fullDataToInsert.push(customers[indexToRemove]);
      customers.splice(indexToRemove, 1);
    });
    const toIndex = calculateToIndex(customers, e);
    customers.splice(toIndex, 0, ...fullDataToInsert);
    e.component.refresh().catch((error: unknown) => notify(error, 'error', 1000));
    if (props.shouldClearSelection) { e.component.clearSelection(); }
  }, [props.shouldClearSelection]);

  return (
    <DataGrid
      dataSource={customers}
      keyExpr="ID"
    >
      <RowDragging
        allowReordering={true}
        dragRender={draggedItemsRender}
        onReorder={reorder as () => void}
        onDragChange={dragChange as () => void}
        onDragStart={dragStart as () => void}
      />
      <Selection mode="multiple" />
      <Sorting mode="none" />
      <Column dataField="ID" width={55} />
      <Column dataField="CompanyName" />
      <Column dataField="Address" />
      <Column dataField="City" />
      <Column dataField="State" />
    </DataGrid>
  );
}

export default DataGridLocalData;
